import { Providers } from "./providers"
import { BusinessProvider } from "./context/BusinessProvider";
import { UserProvider } from "./context/UserProvider";
import { AppointmentProvider } from "./context/AppointmentProvider";
import { ClientProvider } from "./context/ClientProvider";
import { ServiceProvider } from "./context/ServiceProvider";
import { TeamProvider } from "./context/TeamProvider";
import { DrawerProvider } from "./context/DrawerProvider";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body className="antialiased">
          <UserProvider>
            <BusinessProvider>
              <TeamProvider>
                <ServiceProvider>
                  <AppointmentProvider>
                    <ClientProvider>
                      <DrawerProvider>
                        <Providers>{children}</Providers>
                      </DrawerProvider>
                    </ClientProvider>
                  </AppointmentProvider>
                </ServiceProvider>
              </TeamProvider>
            </BusinessProvider>
          </UserProvider>
      </body>
    </html>
  )
}
