import { Providers } from "./providers"
import { BusinessProvider } from "./context/BusinessProvider";
import { UserProvider } from "./context/UserProvider";
import { AppointmentProvider } from "./context/AppointmentProvider";
import { ClientProvider } from "./context/ClientProvider";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body className="antialiased">
          <UserProvider>
            <BusinessProvider>
              <AppointmentProvider>
                <ClientProvider>
                  <Providers>{children}</Providers>
                </ClientProvider>
              </AppointmentProvider>
            </BusinessProvider>
          </UserProvider>
      </body>
    </html>
  )
}
